name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ["1.22"]

    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test
        run: make test

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint
        run: make lint
        env:
          LINTER_FLAGS: '--timeout 5m'

  license-check:
    name: License check
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache licenses
        uses: actions/cache@v4
        with:
          key: licensei-v2-${{ hashFiles('go.sum') }}
          path: |
            .licensei.cache
          restore-keys: |
            licensei-v2

      - name: Download license information for dependencies
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: make license-cache

      - name: Check licenses
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: make license-check
